name: Docker Compose - Self Hosted

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-up:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (Opcional) Login si usas imágenes privadas
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build imágenes definidas en docker-compose
        run: |
          docker compose -f Docker/docker-compose.yml build

      - name: Levantar stack con docker-compose
        run: |
          docker compose -f Docker/docker-compose.yml up -d

      - name: Ver contenedores levantados
        run: docker ps