name: CI - Docker Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  IMAGE_NAME: demoapi-project

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Se asume que el Dockerfile está en la raíz del repo
      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:${{ github.sha }} \
            .

      - name: Build Docker image Dev
        run: |
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:1.0.0-beta \
            .

      - name: Build Docker image QA
        run: |
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:1.0.0-rc.1 \
            .

      - name: Build Docker image Prod
        run: |
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:1.0.0 \
            .

      - name: List Docker images
        run: docker images