- name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # 1. Ponemos el usuario DIRECTO para evitar errores de secretos vacíos
          username: jimmysbroken
          
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .             
          file: Dockerfile        
          push: true
          # Usamos el nombre directo también aquí
          tags: |
            jimmysbroken/${{ env.IMAGE_NAME }}:latest
